# This is a basic workflow to help you get started with Actions

name: CI_sampath

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   check-tools:
      runs-on: ubuntu-latest
  
      steps:
        - name: Print OS Info
          run: |
            echo "OS Version:"
            lsb_release -a
            uname -a
  
        - name: Check Git Version
          run: git --version
  
        - name: Check Node.js and npm
          run: |
            node -v
            npm -v
  
        - name: Check Python Versions
          run: |
            python3 --version
            python3 -m pip --version
  
        - name: Check Java Versions
          run: |
            java -version
            javac -version
  
        - name: Check Docker
          run: |
            docker --version
            docker compose version || docker-compose --version
  
        - name: Check kubectl & Helm
          run: |
            kubectl version --client
            helm version
  
        - name: Check AWS CLI
          run: aws --version
  
        - name: Check GitHub CLI
          run: gh --version
    
